package net.marscraft.xmasevent.quest.commands;

public enum CommandState {
    SUCCESS,
    FAILED,
    QuestCreated,
    QuestAlreadyExists,
    QuestIdWrongFormat,
    CommandSyntaxError,
    CommandSyntaxErrorCreate,
    CommandSyntaxErrorEdit,
    CommandSyntaxErrorQuests,
    CommandSyntaxErrorDelete,
    CantFindQuestId,
    InvalidTaskName,
    InvalidBlock,
    InvalidEntityType,
    InvalidEntityAmount,
    InvalidPlayerName,
    RewardSet,
    CouldNotSetReward,
    StartingMessageSet,
    EndMessageSet,
    DescriptionSet,
    QuestOrderSet,
    CouldNotDeleteQuestFromQuestTable,
    CouldNotDeleteQuestRewards,
    CouldNotDeleteTask,
    CouldNotUpdateQuestOrder,
    CouldNotUpdateQuestIds,
    NoActiveQuestFound,
    QuestFinished,
    CouldNotFinishQuest,
    TaskNotFinished
}
