name: XmasEvent
version: ${project.version}
main: net.marscraft.xmasevent.Main
api-version: 1.17
authors: [ JustKilli ]
description: MarsCraft Christmas Event plugin
website: marscraft.net

commands:
  mcxmas:
    description: MarsCraft Event Command
    permission: mcxmasevent.admin
  quests:
    description: Zeigt deinen Quest fortschritt an
    permission: mcxmasevent.participate
  setquest:
    description: Setzt Spielerquest
